config/routes.rb
WeightBuddy::Application.routes.draw do

  root :to => "home#index"

  devise_for :users, :controllers => { :sessions => "users/sessions" } 

  resources :users, :only => :show
  resources :weights
  match "chart" => "weights#chart"

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :username
  validates_presence_of :username
  validates_uniqueness_of :username, :email, :case_sensitive => false
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
end

app/models/weight.rb
class Weight
  include Mongoid::Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  has_mobile_fu
  has_mobile_fu(true) # forcing mobile view

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @title = "WeightBuddy"

  end

end

app/controllers/users/sessions_controller.rb
# Needed to be able to login with Devise & jQtouch using AJAX queries
# found via Devise Google Group Messages
# http://gist.github.com/418243

class Users::SessionsController < Devise::SessionsController
  def create   
    resource = warden.authenticate!(:scope => resource_name, :recall => "failure")
    set_flash_message :notice, :signed_in 
    sign_in_and_redirect(resource_name, resource)
  end
  
  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope      = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    render "home/index", :mobile => { :success => true, :redirect  => stored_location_for(scope) || after_sign_in_path_for(resource) }, :layout => false
  end
            
  def failure
    render "users/sessions/new", :mobile => {:success => false, :errors => {:reason => "Login failed. Try again"}}, :layout => false
  end   
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    @title = "Userinfo"
  end

end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @title = "Track new Weight"
    @weight = Weight.new
  end
  
  def chart
    @title = "Chart your Weight"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/home/index.html.haml
%h1 Only Mobile Version Available!

app/views/home/index.mobile.haml
#homeIndex
  = render 'shared/header'
  = render 'devise/menu/login_items'
  - if user_signed_in?
    %h2 Welcome, #{current_user.username}
    %ul.rounded
      %li.forward
        =link_to image_tag("icons/track-weight.png", :width => "20", :align => "top", :style => "padding-right: 10px;") + "Track Weight", new_weight_path
      %li.forward
        =link_to image_tag("icons/chart.png", :width => "20", :align => "top", :style => "padding-right: 10px;") + "Chart My Weight", chart_path
    %h2 Administration
  - unless user_signed_in?
    %div.info{:style => "color: #69B; font-size: 110%;"}
      Weight Buddy is a platform to track your weight, daily. And to create nice graphs.
  = render 'devise/menu/registration_items'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Testapp
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    %ul.hmenu
      = render 'devise/menu/registration_items'
      = render 'devise/menu/login_items'
    %p{:style => "color: green"}= notice
    %p{:style => "color: red"}= alert
    = yield

app/views/layouts/application.mobile.haml
!!!
%html
  %head
    %title WeightBuddy
    = stylesheet_link_tag :all
    = stylesheet_link_tag "jqtouch/jqtouch.min.css", "jqtouch/themes/jqt/theme.min.css"
    = javascript_include_tag :defaults
    = javascript_include_tag "jqtouch/jqtouch.min.js", "mobile"
    = csrf_meta_tag
    %body
      #WeightBuddy.current
        = yield
        -# copyright info
        .info
          %p &copy; Pieter Walsweer, #{ link_to "Contact me", "mailto:pieter@walsweer.de" }

app/views/shared/_header.mobile.haml
.toolbar
  %h1= @title
  - unless current_page? root_path
    .back= link_to('Back', "/")
- unless flash.empty?
  %p.info{:style => "color: green"}= notice
  %p.info{:style => "color: red"}= alert

app/views/users/show.mobile.haml
#usersShow
  = render 'shared/header'
  .info
    User: #{@user.username}

app/views/weights/new.mobile.haml
#homeIndex
  = render 'shared/header'

  %div.info
    (Form to enter new weight)